### ISSUE TITLE
Coderdata build_all script does not update download location

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/coderdata#202]
I ran the build_all script yet the yaml file is still the same:
https://github.com/PNNL-CompBio/coderdata/blob/main/coderdata/download/figshare_latest.yml

**Comment by sgosline** [comment]
New data is on figshare but is not downloaded by the package despite running the `build_all` script with the pypi flag.

https://figshare.com/articles/dataset/CODERData0_1_4/26409316. Current version is 0.1.4.

**Comment by jjacobson95** [comment]
Not a lot of details to reproduce this issue here.  Looks like a lot of changes to the repo since I've been out as well. 

Could you provide the following:
- Environment: 
  - If AWS, please provide AMI, Instance type, Architecture, storage amount. Or a link directly to your instance (and connect permissions).
- Command script(s) to setup the environment. Looks like my old setup script needs some adjustments as coderdata/requirements.txt has been separated into 1 file per dataset.
    - If you don't have a command script, I need Python version, Docker version, Docker Compose Version. 
 - Full Coderdata build Command
   - **Example**:   nohup python3.10 build/build_all.py --all --pypi --figshare --version 0.1.41 > output.log 2>&1 &

I did notice a small bug at the end of the [build_all.py](https://github.com/PNNL-CompBio/coderdata/blob/main/build/build_all.py#L334) script, that should make this confirm that the args.figshare and figshare_token are not checked before attempting to upload to pypi but I don't think this should have effected your run, although without more details, I wont know.

**Comment by jjacobson95** [comment]
I think this was pushing but not updating latest version on PyPI. 

Latest version (0.1.40): https://pypi.org/project/coderdata/

Previous attempt (0.1.4):  https://pypi.org/project/coderdata/0.1.4/
