### ISSUE TITLE
Created versioned script/docker that builds entire dataset in root of build directory

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/coderdata#45]
To ensure reproducibility of the data package, we should have a single script (or docker container, or set of docker containers) that builds each dataset in order and uploads to Figshare. 

What should the architecture be? Could we run each dataset in its own docker as a github action? I'm open to ideas.

**Comment by sgosline** [comment]
Using Docker and github actions can be independent for now. We can just create the docker files at least.

**Comment by jjacobson95** [comment]
Some notes -

- The HCMI docker image oom kills consistently (error 137). But this is the same exact [error](https://github.com/PNNL-CompBio/candleDataProcessing/actions/runs/6021402159/job/16334204427#step:6:7471) I was previously getting with GitHub actions. So I think it is related to docker rather than github actions. If I get docker working locally, I think this should be transferable to GitHub actions. 
  - Fixing this will take some debugging and overhaul to the HCMI script.
- There is also the possible timeout concern with GitHub actions (particularly for curve fitting), but we can worry about that later.
- BeatAML docker image is working locally. I'll work on HMCI and the others more next week.

**Comment by sgosline** [comment]
Ahh, this is interesting! Maybe it's a network issue?

**Comment by jjacobson95** [comment]
I just tracked down the logs, and it's definitely an OOM-kill issue in the copy_number portion. The transcriptomics part is working locally, and the mutations section previously worked with GitHub Actions. I think this could most simply be resolved by just using a less memory-intensive alternative to pandas!

**Comment by sgosline** [comment]
this is done.
